apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYmFydmFkIiwicGFzc3dvcmQiOiJnaHBfdmduMmRiQ2RkZ1B6WlNsVnhNTDNjcklSQm1kQ285MVBpUjU1IiwiYXV0aCI6IlltRnlkbUZrT21kb2NGOTJaMjR5WkdKRFpHUm5VSHBhVTJ4V2VFMU1NMk55U1ZKQ2JXUkRiemt4VUdsU05UVT0ifX19
type: kubernetes.io/dockerconfigjson
